/*
* Automatically generated by 'ng g ng-alain:plugin icon'
* @see https://ng-alain.com/cli/plugin#icon
*/

import {
  AppstoreOutline,
  ArrowDownOutline,
  CloudOutline,
  CopyrightOutline,
  FileOutline,
  FullscreenExitOutline,
  FullscreenOutline,
  GithubOutline,
  LockOutline,
  LogoutOutline,
  MailOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  MobileOutline,
  PayCircleOutline,
  PrinterOutline,
  ScanOutline,
  SearchOutline,
  SettingOutline,
  StarOutline,
  TeamOutline,
  ToolOutline,
  UserOutline,
  WechatOutline
} from '@ant-design/icons-angular/icons';

export const ICONS_AUTO = [
  AppstoreOutline,
  ArrowDownOutline,
  CloudOutline,
  CopyrightOutline,
  FileOutline,
  FullscreenExitOutline,
  FullscreenOutline,
  GithubOutline,
  LockOutline,
  LogoutOutline,
  MailOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  MobileOutline,
  PayCircleOutline,
  PrinterOutline,
  ScanOutline,
  SearchOutline,
  SettingOutline,
  StarOutline,
  TeamOutline,
  ToolOutline,
  UserOutline,
  WechatOutline
];
